services:
  - type: static_site
    name: moverbot
    env: static
    branch: main
    buildCommand: cd moverbot && npm install && npm run build
    publishPath: moverbotthe1st/moverbot/dist/moverbot
    plan: free